esphome:
  name: esp32-p4-satellite
  friendly_name: "ESP32-P4 Voice Satellite"
  project:
    name: "waveshare.esp32-p4-micro"
    version: "1.3"

esp32:
  board: esp32-p4-evboard
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes

logger:
  hardware_uart: UART0
  level: VERY_VERBOSE
  logs:
    microphone: VERY_VERBOSE
    voice_assistant: DEBUG
    i2s_audio: DEBUG

# -------------------------------------------------------------------
# NETZWERK ANBINDUNG ÜBER ETHERNET (LAN)
# -------------------------------------------------------------------
ethernet:
  type: IP101
  mdc_pin: GPIO31
  mdio_pin: GPIO52
  power_pin: GPIO51
  clk:
    mode: CLK_EXT_IN
    pin: GPIO50
  phy_addr: 1

# -------------------------------------------------------------------
# HOME ASSISTANT / API & OTA
# -------------------------------------------------------------------
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret wifi_password

# -------------------------------------------------------------------
# I2C & AUDIO CODEC (ES8311)
# -------------------------------------------------------------------
i2c:
  sda: GPIO7
  scl: GPIO8
  scan: true
  id: bus_a

audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: bus_a
    address: 0x18
    use_mclk: True
    use_microphone: true
    mic_gain: 42DB
    sample_rate: 16000
    bits_per_sample: 16bit

# -------------------------------------------------------------------
# I2S AUDIO BUS
# -------------------------------------------------------------------
i2s_audio:
  - id: i2s_bus
    i2s_mclk_pin: GPIO13
    i2s_bclk_pin: GPIO12
    i2s_lrclk_pin: GPIO10
    use_legacy: false

# -------------------------------------------------------------------
# AUDIO PIPELINE (Mixer & Resampler)
# -------------------------------------------------------------------
speaker:
  - platform: i2s_audio
    id: i2s_speaker_out
    dac_type: external
    i2s_audio_id: i2s_bus
    i2s_dout_pin: GPIO9
    audio_dac: es8311_dac
    channel: mono

  - platform: mixer
    id: main_audio_mixer
    output_speaker: i2s_speaker_out
    source_speakers:
      - id: media_spk_mixer_input
      - id: announcement_spk_mixer_input

  - platform: resampler
    id: media_spk_resampler
    output_speaker: media_spk_mixer_input

  - platform: resampler
    id: announcement_spk_resampler
    output_speaker: announcement_spk_mixer_input

# -------------------------------------------------------------------
# MEDIA PLAYER
# -------------------------------------------------------------------
media_player:
  - platform: speaker
    name: "ESP32-P4 Radio"
    id: speaker_media_player
    media_pipeline:
      speaker: media_spk_resampler
    announcement_pipeline:
      speaker: announcement_spk_resampler
    codec_support_enabled: true

# -------------------------------------------------------------------
# MIKROFON (RECORDING)
# -------------------------------------------------------------------
microphone:
  - platform: i2s_audio
    id: my_mic
    i2s_audio_id: i2s_bus
    i2s_din_pin: GPIO11
    adc_type: external
    pdm: false
    bits_per_sample: 16bit

sensor:
  - platform: sound_level
    name: "Microphone Noise Level"
    id: my_sound_level
    microphone: my_mic
    update_interval: 1s

# -------------------------------------------------------------------
# VOICE ASSISTANT (openWakeWord)
# -------------------------------------------------------------------
voice_assistant:
  id: va
  microphone: my_mic
  speaker: announcement_spk_resampler 
  use_wake_word: true

# -------------------------------------------------------------------
# VERSTÄRKER KONTROLLE (NS4150B)
# -------------------------------------------------------------------
switch:
  - platform: gpio
    pin: GPIO53
    name: "Amplifier Enable"
    id: amp_enable
    restore_mode: ALWAYS_ON

# -------------------------------------------------------------------
# MANUELLE KONTROLLEN (DEBUGGING)
# -------------------------------------------------------------------
button:
  - platform: template
    name: "Manual Voice Assist Start"
    id: manual_va_start
    on_press:
      - voice_assistant.start:
      - logger.log: "Manuelle Aktivierung des Voice Assistant angefordert"

  - platform: template
    name: "Manual Voice Assist Stop"
    id: manual_va_stop
    on_press:
      - voice_assistant.stop:

# Status-Sensoren für Debugging
text_sensor:
  - platform: template
    name: "Voice Assistant State"
    id: va_state
    lambda: |-
      if (id(va).is_running()) return {"Listening/Running"};
      return {"Idle/Stopped"};
    update_interval: 2s
