esphome:
  name: esp32-p4-satellite
  friendly_name: "ESP32-P4 Voice Satellite"
  project:
    name: "WAVESHARE-ESP32-P4-WIFI6-DEV-KIT-MICROPHONE-FOR-HOME-ASSISTANT"
    version: "1.22"
  on_boot:
    - priority: 100.0
      then:
        - lambda: |-
            // Initial analog mic fix + default gain (30dB = 0xA)
            // Register 0x14: Bit 6=0, Bits 0-3=0xA -> 0x1A
            id(es8311_dac).write_byte(0x14, 0x1A);
            ESP_LOGI("es8311_fix", "Analog Mic Mode forced on boot (30dB)");

esp32:
  board: esp32-p4-evboard
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes

logger:
  hardware_uart: UART0
  level: DEBUG
  logs:
    voice_assistant: DEBUG
    microphone: DEBUG
    i2s_audio: DEBUG
    component: INFO

# -------------------------------------------------------------------
# NETZWERK ANBINDUNG
# -------------------------------------------------------------------
ethernet:
  type: IP101
  mdc_pin: GPIO31
  mdio_pin: GPIO52
  power_pin: GPIO51
  clk:
    mode: CLK_EXT_IN
    pin: GPIO50
  phy_addr: 1

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret wifi_password

# -------------------------------------------------------------------
# I2C & AUDIO CODEC (ES8311)
# -------------------------------------------------------------------
i2c:
  sda: GPIO7
  scl: GPIO8
  scan: true
  id: bus_a
  frequency: 100kHz

audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: bus_a
    address: 0x18
    use_mclk: True
    use_microphone: true
    mic_gain: 30DB
    sample_rate: 16000
    bits_per_sample: 16bit

# -------------------------------------------------------------------
# I2S AUDIO BUS
# -------------------------------------------------------------------
i2s_audio:
  - id: i2s_bus
    i2s_mclk_pin: GPIO13
    i2s_bclk_pin: GPIO12
    i2s_lrclk_pin: GPIO10
    use_legacy: false

# -------------------------------------------------------------------
# AUDIO PIPELINE
# -------------------------------------------------------------------
speaker:
  - platform: i2s_audio
    id: i2s_speaker_out
    dac_type: external
    i2s_audio_id: i2s_bus
    i2s_dout_pin: GPIO9
    audio_dac: es8311_dac
    channel: mono

  - platform: mixer
    id: main_audio_mixer
    output_speaker: i2s_speaker_out
    source_speakers:
      - id: media_spk_mixer_input
      - id: announcement_spk_mixer_input

  - platform: resampler
    id: media_spk_resampler
    output_speaker: media_spk_mixer_input

  - platform: resampler
    id: announcement_spk_resampler
    output_speaker: announcement_spk_resampler

# -------------------------------------------------------------------
# MEDIA PLAYER
# -------------------------------------------------------------------
media_player:
  - platform: speaker
    name: "ESP32-P4 Radio"
    id: speaker_media_player
    media_pipeline:
      speaker: media_spk_resampler
    announcement_pipeline:
      speaker: announcement_spk_resampler
    codec_support_enabled: true

# -------------------------------------------------------------------
# MIKROFON
# -------------------------------------------------------------------
microphone:
  - platform: i2s_audio
    id: my_mic
    i2s_audio_id: i2s_bus
    i2s_din_pin: GPIO11
    adc_type: external
    pdm: false
    bits_per_sample: 16bit
    channel: left

# -------------------------------------------------------------------
# VOICE ASSISTANT
# -------------------------------------------------------------------
voice_assistant:
  id: va
  microphone: my_mic
  speaker: announcement_spk_resampler 
  use_wake_word: true
  noise_suppression_level: 2
  on_listening:
    - logger.log: "Voice Assistant started listening..."
  on_error:
    - logger.log: "Voice Assistant Error!"

# -------------------------------------------------------------------
# EXPOSED CONTROLS (HOME ASSISTANT)
# -------------------------------------------------------------------
number:
  - platform: template
    name: "Microphone Gain"
    id: mic_gain_control
    min_value: 0
    max_value: 42
    step: 3
    unit_of_measurement: "dB"
    initial_value: 30
    optimistic: true
    on_value:
      - lambda: |-
          // ES8311 Register 0x14: Bits 0-3 = Gain (0-14), Bit 6 = Analog (0)
          uint8_t index = (uint8_t)(x / 3.0);
          if (index > 14) index = 14; 
          uint8_t reg_val = 0x10 | index; 
          id(es8311_dac).write_byte(0x14, reg_val);
          ESP_LOGI("config", "ES8311 Mic Gain set to: %.0f dB (Reg 0x14: 0x%02X)", x, reg_val);

  - platform: template
    name: "Noise Suppression Level"
    id: ns_level_control
    min_value: 0
    max_value: 4
    step: 1
    initial_value: 2
    optimistic: true
    on_value:
      - lambda: |-
          ESP_LOGI("config", "New Noise Suppression Level: %.0f", x);

  - platform: template
    name: "Speaker Volume"
    id: spk_volume_control
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"
    initial_value: 80
    optimistic: true
    on_value:
      - lambda: |-
          // ES8311 Reg 0x32: Volume control
          uint8_t reg_val = (uint8_t)((100.0 - x) * 1.9); 
          id(es8311_dac).write_byte(0x32, reg_val);
          ESP_LOGI("config", "Speaker Volume set to: %.0f%% (Reg 0x32: 0x%02X)", x, reg_val);

# -------------------------------------------------------------------
# VERSTÄRKER KONTROLLE
# -------------------------------------------------------------------
switch:
  - platform: gpio
    pin: GPIO53
    name: "Amplifier Enable"
    id: amp_enable
    restore_mode: ALWAYS_ON

# -------------------------------------------------------------------
# MANUELLE KONTROLLEN
# -------------------------------------------------------------------
button:
  - platform: template
    name: "Manual Voice Assist Start"
    id: manual_va_start
    on_press:
      - voice_assistant.start:

  - platform: template
    name: "Manual Voice Assist Stop"
    id: manual_va_stop
    on_press:
      - voice_assistant.stop:

text_sensor:
  - platform: template
    name: "Voice Assistant State"
    id: va_state
    lambda: |-
      if (id(va).is_running()) return {"Listening/Running"};
      return {"Idle/Stopped"};
    update_interval: 2s
